### ISSUE TITLE
Crowdsourcing names, incentives and method

### ISSUE THREAD

**Issue by sunitaparbhu** [sunitaparbhu/project-template#1]
### Summary
Move from doing research inhouse to becoming an aggregator of crowd-sourced content. The PLN network and PL partners contain significant expertise that is tried and tested. 

### Intended Outcome
A distribution list that shows who we can “ask for help”.  CRM-type tracking on who has been asked to contribute and what they have contributed. Mechanics such as a central email address from which to send requests, and a standardized form or email to gather knowledge that makes it easy for us to synthesize and maintain knowledge. 

### Tasks for this Story

- [ ] List of partners who can provide free assistance, such as Sequoia.
- [ ] Which PLN companies can provide the expertise that we can re-package for other PLN companies. Note 90% of PLN are US entities, so this involves talking to the 10% that are not US entities. e.g. PowerLoom for India expertise.
- [ ] What is in it for them? Recognition? E.g. a thank you email that goes out every month showing who has helped with what.Get advice from Mosaia on what has worked for them.
- [ ] **Launch the feature:**
