### ISSUE TITLE
Build a clear view of demand

### ISSUE THREAD

**Issue by sunitaparbhu** [sunitaparbhu/project-template#6]
### Summary
Expand focus from entities formed in the US and select European countries to entities formed in other jurisdictions (rest of Europe, Asia, Africa). Expand target segments that we can serve to include: DAOs, Grant programs and Protocols. 

Given how large this scope could be, analyze demand to identify the countries and topics to focus on. 

### Intended Outcome
A set of priorities that we should pursue in the expansion of vendors/services research, with reasons for their selection. For example:  
- In France, benefits plans
- In India, vendors for setting up individual contractor companies and health insurance
- For USA, a low cost HR person e.g. to fill out forms for employer registration
- For DAOs, KYC services, with high priority countrues x, y, z 
- For Protocols like Filecoin, payment options, with high priority countrues x, y, z 

### Tasks for this story
- [ ] Mine the data from PL Ventures, Spaceport Directory, and Talent Funnel to determine the highest priority countries.  Also, identify entities that operate as DAOs, Grant programs, or Protocols (likely a small percentage of the total, under 10%)
- [ ] Interview PLN companies to establish their granular needs where they would want us to do the search/recommendation for them (do they need KYC, 401k plans, etc)
- [ ] Launch the feature. Present research to stakeholders and obtain buy-in about the target segments we’re going to build for. (Chris, Spaceport, recruiting and people teams, PL Ventures)
